# Generated by Django 4.2.3 on 2023-09-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('age', models.IntegerField(max_length=2)),
                ('gender', models.CharField(max_length=8)),
                ('weight', models.IntegerField(max_length=3)),
            ],
        ),
    ]
