# Generated by Django 4.2.3 on 2023-09-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_trait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trait',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trait',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
